const state={data:null,packs:{},active:"🎲 Random Mix",cards:[],idx:0,scoreA:0,scoreB:0,roundScore:0,timeLeft:90,timer:null,running:false,recent:[]};
const $=id=>document.getElementById(id);
function normalize(card){const [word,category,emoji,color]=card;return{word,category,emoji,color,id:`${word}|${category}`}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function loadRecent(){try{state.recent=JSON.parse(localStorage.recentCards||"[]")}catch{state.recent=[]}}
function saveRecent(){localStorage.recentCards=JSON.stringify(state.recent.slice(0,80))}
function buildPacks(raw){const unique=new Map();Object.values(raw.packs).flat().forEach(c=>{const n=normalize(c);unique.set(n.id,c)});return{[raw.defaultPack||"🎲 Random Mix"]:[...unique.values()],...raw.packs}}
function setupSelects(){for(const id of["packSelect","packIntro"]){const s=$(id);s.innerHTML=Object.keys(state.packs).map(n=>`<option value="${n}">${n}</option>`).join("");s.value=state.active;s.onchange=()=>{state.active=s.value;$("packSelect").value=state.active;$("packIntro").value=state.active;loadDeck();resetGame(false)}}}
function freshDeck(){const pool=state.packs[state.active].map(normalize);let fresh=pool.filter(c=>!state.recent.includes(c.id));if(fresh.length<Math.min(25,Math.ceil(pool.length*.35))){state.recent=[];saveRecent();fresh=pool.slice()}shuffle(fresh);const used=new Set(fresh.map(c=>c.id));const rest=shuffle(pool.filter(c=>!used.has(c.id)));return fresh.concat(rest)}
function loadDeck(){state.cards=freshDeck();state.idx=0;$("packBadge").textContent=state.active;render()}
function markSeen(c){if(!c)return;state.recent=[c.id,...state.recent.filter(x=>x!==c.id)].slice(0,80);saveRecent()}
function render(){if(!state.cards.length)return;const c=state.cards[state.idx%state.cards.length];$("word").textContent=c.word;$("category").textContent=c.category;$("emoji").textContent=c.emoji;$("card").style.borderColor=c.color;$("catPill").style.background=c.color;document.documentElement.style.setProperty("--a",c.color);$("counter").textContent=`${state.idx%state.cards.length+1} / ${state.cards.length}`;$("roundScore").textContent=`Lượt này: ${state.roundScore}`}
function nextCard(){markSeen(state.cards[state.idx%state.cards.length]);state.idx++;if(state.idx>=state.cards.length-1){state.cards=freshDeck();state.idx=0}render()}
function passCard(){flash("BỎ QUA","var(--r)");nextCard()}
function correct(team){state.roundScore++;if(team==="A")$("scoreA").textContent=++state.scoreA;if(team==="B")$("scoreB").textContent=++state.scoreB;confetti(team);flash("+1","var(--g)");nextCard()}
function flash(text,bg){const f=$("flash");f.textContent=text;f.style.background=bg;f.classList.remove("show");void f.offsetWidth;f.classList.add("show")}
function confetti(team){const layer=$("confettiLayer");if(!layer)return;const right=team==="B";const colors=["#12b76a","#ff6b6b","#fdb022","#4d96ff","#b983ff","#2ec4b6"];for(let i=0;i<34;i++){const p=document.createElement("span");p.className="confetti"+(right?" right":"");p.style.left=right?"calc(100vw - 18px)":"8px";p.style.top=`${18+Math.random()*68}vh`;p.style.background=colors[i%colors.length];p.style.setProperty("--dx",`${160+Math.random()*520}px`);p.style.setProperty("--dy",`${-160+Math.random()*320}px`);p.style.setProperty("--rot",`${-360+Math.random()*720}deg`);p.style.animationDelay=`${Math.random()*90}ms`;layer.appendChild(p);setTimeout(()=>p.remove(),1100)}}
function resetTimer(){clearInterval(state.timer);state.timer=null;state.running=false;state.timeLeft=90;$("timer").textContent=state.timeLeft;$("timer").style.color="#fff";$("timerBtn").textContent="▶ 90s"}
function toggleTimer(){if(state.running)return resetTimer();state.running=true;$("timerBtn").textContent="↺ Reset";state.timer=setInterval(()=>{state.timeLeft--;$("timer").textContent=state.timeLeft;if(state.timeLeft<=10)$("timer").style.color="var(--y)";if(state.timeLeft<=0){resetTimer();flash("HẾT GIỜ","rgba(0,0,0,.72)");setTimeout(()=>alert("Hết giờ! Đổi người đoán hoặc đổi đội."),120)}},1000)}
function newRound(start=true){resetTimer();state.roundScore=0;state.cards=freshDeck();state.idx=0;render();if(start)toggleTimer()}
function resetGame(start=false){resetTimer();state.scoreA=0;state.scoreB=0;state.roundScore=0;$("scoreA").textContent="0";$("scoreB").textContent="0";state.cards=freshDeck();state.idx=0;render();if(start)toggleTimer()}
function startGame(){$("intro").classList.add("hidden");newRound(true)}
function bindEvents(){$("startBtn").addEventListener("click",startGame);$("timerBtn").addEventListener("click",toggleTimer);$("passBtn").addEventListener("click",passCard);$("nextBtn").addEventListener("click",nextCard);$("newRoundBtn").addEventListener("click",()=>resetGame(false));document.querySelectorAll(".correct").forEach(btn=>btn.addEventListener("click",()=>correct(btn.dataset.team)));document.addEventListener("keydown",e=>{const k=e.key;if(k==="ArrowLeft"){e.preventDefault();correct("A")}else if(k==="ArrowRight"){e.preventDefault();correct("B")}else if(k==="ArrowDown"||k===" "){e.preventDefault();passCard()}else if(k.toLowerCase()==="t")toggleTimer();else if(k.toLowerCase()==="r")resetGame(false)})}
async function init(){bindEvents();loadRecent();try{const res=await fetch("cards.json",{cache:"no-store"});if(!res.ok)throw new Error(`cards.json ${res.status}`);state.data=await res.json();state.packs=buildPacks(state.data);state.active=state.data.defaultPack||"🎲 Random Mix";setupSelects();loadDeck()}catch(err){console.error(err);$("word").textContent="Lỗi tải thẻ";$("loadError").classList.remove("hidden")}}
init();